### ISSUE TITLE
InterfaceCEREMA not working on Archlinux

### ISSUE THREAD

**Issue by jujudusud** [micmacIGN/InterfaceCEREMA#10]
When trying to lunch AperoDeDenis.py with :

> python3 AperoDeDenis.py

> Traceback (most recent call last):
  File "AperoDeDenis.py", line 296, in <module>
    from tkinter import *                       # gestion des fenêtre, des boutons ,des menus
  File "/usr/lib/python3.8/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory

**Comment by jujudusud** [comment]
Ok, Installing tk package solve my problem.
All is working well now.
