### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by XRolland** [micmacIGN/InterfaceCEREMA#5]
I always got this error on build 5.21 build (using the win64 .msi from GitHub)
launching one of these commands : 
 **Tools > Nom et Focale de l’appareil photo, dimension des photos**
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\denis.jouin\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1699, in __call__
  File "AperoDeDenis.py", line 6614, in OutilAppareilPhoto
  File "AperoDeDenis.py", line 6690, in tagExif
TypeError: list indices must be integers or slices, not tuple
```

**Tools > Mettre à jour DicoCamera.xml**
```
Traceback (most recent call last):
  File "C:\Users\denis.jouin\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1699, in __call__
  File "AperoDeDenis.py", line 6766, in miseAJourDicoCamera
  File "AperoDeDenis.py", line 9527, in nombreDeExifTagDifferents
  File "AperoDeDenis.py", line 9527, in <listcomp>
  File "AperoDeDenis.py", line 6690, in tagExif
TypeError: list indices must be integers or slices, not tuple
```

**MicMac > lancer micmac**
```
le 7/2/2019 à 11:15:34 Launching AperoDeDenis V 5.21.
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\denis.jouin\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1699, in __call__
  File "AperoDeDenis.py", line 5276, in lanceMicMac
  File "AperoDeDenis.py", line 9527, in nombreDeExifTagDifferents
  File "AperoDeDenis.py", line 9527, in <listcomp>
  File "AperoDeDenis.py", line 6690, in tagExif
TypeError: list indices must be integers or slices, not tuple
```
Micmac fails with no other warning 

**Tools >  toutes les focales et les noms d'appareils photos** 
seems be Ok

Everything fails silenciously.
It seems the command is looking for your profile directory, but is it the real problem?

**Comment by Jouin** [comment]
Version 5.22 fix this issues for new projects.
On the other hand the problem will persist for the projects which you have renamed with the 5.21 version.
The solution is to open the project and then rename it: the concern will disappear.
La version 5.22 supprime ce bug pour les nouveaux chantiers.
Par contre le problème va persister pour les chantiers que vous avez renommés avec la version 5.21.
La solution consiste à ouvrir le chantier puis à le renommer : le souci disparaitra.
